server:
  name: go-sql-hexagonal-architecture-sample
  port: 8080

sql:
  driver: mysql
  data_source: root:123456@/testdb?charset=utf8&parseTime=True&loc=Local

mongo:
  uri: mongodb://127.0.0.1:27017
  database: testdb 
